"""Visual context report generator for the Lumi YOHAS pipeline.

Compiles a FinalReport (with optional embedded figures) into self-contained
HTML, PDF, or JSON outputs.  HTML is the single source of truth -- PDF is
rendered from the same HTML via xhtml2pdf.

Usage::

    from src.reports.generator import ReportGenerator, ReportFigure, FigureType

    gen = ReportGenerator()
    html = await gen.generate_html(report, figures=[...])
    pdf  = await gen.generate_pdf(report, figures=[...])
    json_str = gen.generate_json(report)
"""

from __future__ import annotations

import asyncio
import base64
import io
import json
import logging
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

try:
    from src.utils.types import FinalReport
except ImportError:
    from utils.types import FinalReport  # type: ignore[no-redef]

logger = logging.getLogger("lumi.reports")

_TEMPLATE_DIR = Path(__file__).parent / "templates"

# Placeholder SVG shown when an image cannot be fetched.
_PLACEHOLDER_SVG_RAW = (
    b'<svg xmlns="http://www.w3.org/2000/svg" width="400" height="220">'
    b'<rect width="400" height="220" fill="#F0F5F7" />'
    b'<rect x="1" y="1" width="398" height="218" fill="none" stroke="#D4E4EB" stroke-width="1.5" />'
    # Icon: simple chart/image pictogram
    b'<g transform="translate(170, 60)">'
    b'<rect x="0" y="40" width="12" height="30" fill="#C5D5DE" />'
    b'<rect x="18" y="25" width="12" height="45" fill="#A8C0CC" />'
    b'<rect x="36" y="10" width="12" height="60" fill="#8EAAB8" />'
    b'</g>'
    b'<text x="200" y="145" text-anchor="middle" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" '
    b'font-size="11" fill="#6B8899" font-weight="600">Figure will render with live data</text>'
    b'<text x="200" y="164" text-anchor="middle" font-family="Helvetica Neue, Helvetica, Arial, sans-serif" '
    b'font-size="9" fill="#8EAAB8">Generated by BioRender / MockFlow MCP</text>'
    b'</svg>'
)
_PLACEHOLDER_SVG = "data:image/svg+xml;base64," + base64.b64encode(_PLACEHOLDER_SVG_RAW).decode()


# ---------------------------------------------------------------------------
# Figure model
# ---------------------------------------------------------------------------

class FigureType(str, Enum):
    PATHWAY = "PATHWAY"
    HEATMAP = "HEATMAP"
    MOA = "MOA"
    CONFIDENCE = "CONFIDENCE"
    VOLCANO = "VOLCANO"
    STRUCTURE = "STRUCTURE"
    SURFACE = "SURFACE"
    BINDING_SITE = "BINDING_SITE"
    ALIGNMENT = "ALIGNMENT"
    OTHER = "OTHER"


class ReportFigure(BaseModel):
    """A figure to embed in a generated report."""

    title: str = Field(..., description="Display title for the figure.")
    caption: str = Field(default="", description="Descriptive caption.")
    image_url: str = Field(default="", description="HTTP URL to the figure image (PNG/SVG).")
    file_path: str = Field(default="", description="Local file path to the figure image (PyMOL renders).")
    figure_type: FigureType = Field(default=FigureType.OTHER, description="Semantic type of the figure.")
    source_tool: str = Field(default="", description="Tool that generated this figure.")

    @property
    def embed_key(self) -> str:
        """Key used to look up the base64 data URI in figure_data dict."""
        return self.image_url or self.file_path

    @property
    def type_label(self) -> str:
        """Clean display label for the figure type."""
        _labels = {
            "MOA": "Mechanism of Action", "HEATMAP": "Heatmap", "PATHWAY": "Pathway",
            "VOLCANO": "Volcano Plot", "CONFIDENCE": "Confidence", "STRUCTURE": "3D Structure",
            "SURFACE": "Molecular Surface", "BINDING_SITE": "Binding Site", "ALIGNMENT": "Structural Alignment",
        }
        return _labels.get(self.figure_type.value, self.figure_type.value.replace("_", " ").title())


# ---------------------------------------------------------------------------
# Image fetching helpers
# ---------------------------------------------------------------------------

def _embed_local_file(file_path: str) -> str:
    """Read a local image file and return a base64 data URI, or a placeholder on failure."""
    try:
        path = Path(file_path)
        if not path.exists():
            logger.warning("Local figure not found: %s", file_path)
            return _PLACEHOLDER_SVG
        suffix = path.suffix.lower()
        mime = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".svg": "image/svg+xml", ".gif": "image/gif"}.get(suffix, "image/png")
        encoded = base64.b64encode(path.read_bytes()).decode()
        return f"data:{mime};base64,{encoded}"
    except Exception:
        logger.warning("Failed to read local image: %s", file_path)
        return _PLACEHOLDER_SVG


async def _fetch_and_embed(url: str) -> str:
    """Download an image URL and return a base64 data URI, or a placeholder on failure."""
    try:
        import httpx

        async with httpx.AsyncClient(timeout=30, follow_redirects=True) as client:
            resp = await client.get(url)
            resp.raise_for_status()

        content_type = resp.headers.get("content-type", "image/png").split(";")[0].strip()
        encoded = base64.b64encode(resp.content).decode()
        return f"data:{content_type};base64,{encoded}"
    except Exception:
        logger.warning("Failed to fetch image: %s", url)
        return _PLACEHOLDER_SVG


async def _embed_all_figures(figures: list[ReportFigure]) -> dict[str, str]:
    """Embed all figure images and return {key: data_uri} mapping.

    Handles both URL-based figures (BioRender/MockFlow) and local file-based
    figures (PyMOL renders).
    """
    if not figures:
        return {}

    result: dict[str, str] = {}
    url_figures = [(f.image_url, f) for f in figures if f.image_url]
    file_figures = [(f.file_path, f) for f in figures if f.file_path and not f.image_url]

    # Fetch URL-based figures concurrently
    if url_figures:
        urls = [url for url, _ in url_figures]
        fetched = await asyncio.gather(*[_fetch_and_embed(u) for u in urls])
        for url, data_uri in zip(urls, fetched):
            result[url] = data_uri

    # Read local files (fast, no async needed)
    for file_path, _ in file_figures:
        result[file_path] = _embed_local_file(file_path)

    return result


# ---------------------------------------------------------------------------
# ReportGenerator
# ---------------------------------------------------------------------------

class ReportGenerator:
    """Stateless compiler: FinalReport + figures -> HTML / PDF / JSON."""

    async def generate_html(
        self,
        report: FinalReport,
        figures: list[ReportFigure] | None = None,
    ) -> str:
        """Render *report* to a self-contained HTML string.

        Images referenced by *figures* are downloaded and base64-embedded so
        the HTML file is fully portable.
        """
        from jinja2 import Environment, FileSystemLoader

        figures = figures or _figures_from_report(report)
        figure_data = await _embed_all_figures(figures)

        env = Environment(
            loader=FileSystemLoader(str(_TEMPLATE_DIR)),
            autoescape=True,
        )
        template = env.get_template("report.html")

        return template.render(
            report=report,
            figures=figures,
            figure_data=figure_data,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

    async def generate_pdf(
        self,
        report: FinalReport,
        figures: list[ReportFigure] | None = None,
    ) -> bytes:
        """Render *report* to PDF bytes (generated from the HTML representation)."""
        from xhtml2pdf import pisa

        html = await self.generate_html(report, figures)

        buffer = io.BytesIO()
        pisa_status = pisa.CreatePDF(io.StringIO(html), dest=buffer)
        if pisa_status.err:
            logger.error("xhtml2pdf conversion had %d errors", pisa_status.err)
        return buffer.getvalue()

    def generate_json(self, report: FinalReport) -> str:
        """Serialize *report* to a JSON string with generation metadata."""
        payload: dict[str, Any] = report.model_dump(mode="json")
        payload["_metadata"] = {
            "generator": "lumi-report-generator",
            "version": "0.1.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
        }
        return json.dumps(payload, indent=2, default=str)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _figures_from_report(report: FinalReport) -> list[ReportFigure]:
    """Convert the raw ``report.figures`` dicts into ReportFigure objects.

    Handles both URL-based figures (BioRender/MockFlow) and file-based
    figures (PyMOL renders) by checking for ``image_url`` or ``file_path``.
    """
    out: list[ReportFigure] = []
    for fig in report.figures:
        try:
            # Skip figures with neither image_url nor file_path
            if not fig.get("image_url") and not fig.get("file_path"):
                logger.warning("Skipping figure with no image source: %s", fig)
                continue
            out.append(ReportFigure(**fig))
        except Exception:
            logger.warning("Skipping malformed figure entry: %s", fig)
    return out
